name: MineReloaded
version: VERSION

authors: [FlorestanII, elekt0]

api-version: '1.20'

main: minereloaded.MineReloaded

commands:
    testspawn:
        description: "This is a test command to spawn a custom entity"
        usage: "/testspawn"
